# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.latent_symbol import LatentSymbol
from openapi_server import util

from openapi_server.models.latent_symbol import LatentSymbol  # noqa: E501

class ObservableSymbol(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, superposed_character=None):  # noqa: E501
        """ObservableSymbol - a model defined in OpenAPI

        :param superposed_character: The superposed_character of this ObservableSymbol.  # noqa: E501
        :type superposed_character: List[LatentSymbol]
        """
        self.openapi_types = {
            'superposed_character': List[LatentSymbol]
        }

        self.attribute_map = {
            'superposed_character': 'superposedCharacter'
        }

        self._superposed_character = superposed_character

    @classmethod
    def from_dict(cls, dikt) -> 'ObservableSymbol':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ObservableSymbol of this ObservableSymbol.  # noqa: E501
        :rtype: ObservableSymbol
        """
        return util.deserialize_model(dikt, cls)

    @property
    def superposed_character(self):
        """Gets the superposed_character of this ObservableSymbol.

        The segments (sub-keys) that compose the permanent identifier.  # noqa: E501

        :return: The superposed_character of this ObservableSymbol.
        :rtype: List[LatentSymbol]
        """
        return self._superposed_character

    @superposed_character.setter
    def superposed_character(self, superposed_character):
        """Sets the superposed_character of this ObservableSymbol.

        The segments (sub-keys) that compose the permanent identifier.  # noqa: E501

        :param superposed_character: The superposed_character of this ObservableSymbol.
        :type superposed_character: List[LatentSymbol]
        """

        self._superposed_character = superposed_character
