# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.point2_d import Point2D
from openapi_server.models.shape2_d_polygon import Shape2DPolygon
from openapi_server.models.shape2_d_rectangle_text_block_all_of import Shape2DRectangleTextBlockAllOf
from openapi_server.models.style import Style
from openapi_server.models.transliteration import Transliteration
from openapi_server import util

from openapi_server.models.point2_d import Point2D  # noqa: E501
from openapi_server.models.shape2_d_polygon import Shape2DPolygon  # noqa: E501
from openapi_server.models.shape2_d_rectangle_text_block_all_of import Shape2DRectangleTextBlockAllOf  # noqa: E501
from openapi_server.models.style import Style  # noqa: E501
from openapi_server.models.transliteration import Transliteration  # noqa: E501

class Shape2DPolygonTextBlock(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, shape_id=None, shape_type=None, points=None, transliteration=None, style=None):  # noqa: E501
        """Shape2DPolygonTextBlock - a model defined in OpenAPI

        :param shape_id: The shape_id of this Shape2DPolygonTextBlock.  # noqa: E501
        :type shape_id: str
        :param shape_type: The shape_type of this Shape2DPolygonTextBlock.  # noqa: E501
        :type shape_type: str
        :param points: The points of this Shape2DPolygonTextBlock.  # noqa: E501
        :type points: List[Point2D]
        :param transliteration: The transliteration of this Shape2DPolygonTextBlock.  # noqa: E501
        :type transliteration: Transliteration
        :param style: The style of this Shape2DPolygonTextBlock.  # noqa: E501
        :type style: Style
        """
        self.openapi_types = {
            'shape_id': str,
            'shape_type': str,
            'points': List[Point2D],
            'transliteration': Transliteration,
            'style': Style
        }

        self.attribute_map = {
            'shape_id': 'shapeId',
            'shape_type': 'shapeType',
            'points': 'points',
            'transliteration': 'transliteration',
            'style': 'style'
        }

        self._shape_id = shape_id
        self._shape_type = shape_type
        self._points = points
        self._transliteration = transliteration
        self._style = style

    @classmethod
    def from_dict(cls, dikt) -> 'Shape2DPolygonTextBlock':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Shape2DPolygonTextBlock of this Shape2DPolygonTextBlock.  # noqa: E501
        :rtype: Shape2DPolygonTextBlock
        """
        return util.deserialize_model(dikt, cls)

    @property
    def shape_id(self):
        """Gets the shape_id of this Shape2DPolygonTextBlock.

        [TBD] Alpha-numeric, unique id of dataset  # noqa: E501

        :return: The shape_id of this Shape2DPolygonTextBlock.
        :rtype: str
        """
        return self._shape_id

    @shape_id.setter
    def shape_id(self, shape_id):
        """Sets the shape_id of this Shape2DPolygonTextBlock.

        [TBD] Alpha-numeric, unique id of dataset  # noqa: E501

        :param shape_id: The shape_id of this Shape2DPolygonTextBlock.
        :type shape_id: str
        """
        if shape_id is None:
            raise ValueError("Invalid value for `shape_id`, must not be `None`")  # noqa: E501

        self._shape_id = shape_id

    @property
    def shape_type(self):
        """Gets the shape_type of this Shape2DPolygonTextBlock.

        descriminator  # noqa: E501

        :return: The shape_type of this Shape2DPolygonTextBlock.
        :rtype: str
        """
        return self._shape_type

    @shape_type.setter
    def shape_type(self, shape_type):
        """Sets the shape_type of this Shape2DPolygonTextBlock.

        descriminator  # noqa: E501

        :param shape_type: The shape_type of this Shape2DPolygonTextBlock.
        :type shape_type: str
        """
        if shape_type is None:
            raise ValueError("Invalid value for `shape_type`, must not be `None`")  # noqa: E501

        self._shape_type = shape_type

    @property
    def points(self):
        """Gets the points of this Shape2DPolygonTextBlock.


        :return: The points of this Shape2DPolygonTextBlock.
        :rtype: List[Point2D]
        """
        return self._points

    @points.setter
    def points(self, points):
        """Sets the points of this Shape2DPolygonTextBlock.


        :param points: The points of this Shape2DPolygonTextBlock.
        :type points: List[Point2D]
        """

        self._points = points

    @property
    def transliteration(self):
        """Gets the transliteration of this Shape2DPolygonTextBlock.


        :return: The transliteration of this Shape2DPolygonTextBlock.
        :rtype: Transliteration
        """
        return self._transliteration

    @transliteration.setter
    def transliteration(self, transliteration):
        """Sets the transliteration of this Shape2DPolygonTextBlock.


        :param transliteration: The transliteration of this Shape2DPolygonTextBlock.
        :type transliteration: Transliteration
        """

        self._transliteration = transliteration

    @property
    def style(self):
        """Gets the style of this Shape2DPolygonTextBlock.


        :return: The style of this Shape2DPolygonTextBlock.
        :rtype: Style
        """
        return self._style

    @style.setter
    def style(self, style):
        """Sets the style of this Shape2DPolygonTextBlock.


        :param style: The style of this Shape2DPolygonTextBlock.
        :type style: Style
        """

        self._style = style
