# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.point2_d import Point2D
from openapi_server.models.shape import Shape
from openapi_server.models.shape2_d_polygon_all_of import Shape2DPolygonAllOf
from openapi_server import util

from openapi_server.models.point2_d import Point2D  # noqa: E501
from openapi_server.models.shape import Shape  # noqa: E501
from openapi_server.models.shape2_d_polygon_all_of import Shape2DPolygonAllOf  # noqa: E501

class Shape2DPolygon(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, shape_id=None, shape_type=None, points=None):  # noqa: E501
        """Shape2DPolygon - a model defined in OpenAPI

        :param shape_id: The shape_id of this Shape2DPolygon.  # noqa: E501
        :type shape_id: str
        :param shape_type: The shape_type of this Shape2DPolygon.  # noqa: E501
        :type shape_type: str
        :param points: The points of this Shape2DPolygon.  # noqa: E501
        :type points: List[Point2D]
        """
        self.openapi_types = {
            'shape_id': str,
            'shape_type': str,
            'points': List[Point2D]
        }

        self.attribute_map = {
            'shape_id': 'shapeId',
            'shape_type': 'shapeType',
            'points': 'points'
        }

        self._shape_id = shape_id
        self._shape_type = shape_type
        self._points = points

    @classmethod
    def from_dict(cls, dikt) -> 'Shape2DPolygon':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Shape2DPolygon of this Shape2DPolygon.  # noqa: E501
        :rtype: Shape2DPolygon
        """
        return util.deserialize_model(dikt, cls)

    @property
    def shape_id(self):
        """Gets the shape_id of this Shape2DPolygon.

        [TBD] Alpha-numeric, unique id of dataset  # noqa: E501

        :return: The shape_id of this Shape2DPolygon.
        :rtype: str
        """
        return self._shape_id

    @shape_id.setter
    def shape_id(self, shape_id):
        """Sets the shape_id of this Shape2DPolygon.

        [TBD] Alpha-numeric, unique id of dataset  # noqa: E501

        :param shape_id: The shape_id of this Shape2DPolygon.
        :type shape_id: str
        """
        if shape_id is None:
            raise ValueError("Invalid value for `shape_id`, must not be `None`")  # noqa: E501

        self._shape_id = shape_id

    @property
    def shape_type(self):
        """Gets the shape_type of this Shape2DPolygon.

        descriminator  # noqa: E501

        :return: The shape_type of this Shape2DPolygon.
        :rtype: str
        """
        return self._shape_type

    @shape_type.setter
    def shape_type(self, shape_type):
        """Sets the shape_type of this Shape2DPolygon.

        descriminator  # noqa: E501

        :param shape_type: The shape_type of this Shape2DPolygon.
        :type shape_type: str
        """
        if shape_type is None:
            raise ValueError("Invalid value for `shape_type`, must not be `None`")  # noqa: E501

        self._shape_type = shape_type

    @property
    def points(self):
        """Gets the points of this Shape2DPolygon.


        :return: The points of this Shape2DPolygon.
        :rtype: List[Point2D]
        """
        return self._points

    @points.setter
    def points(self, points):
        """Sets the points of this Shape2DPolygon.


        :param points: The points of this Shape2DPolygon.
        :type points: List[Point2D]
        """

        self._points = points
