# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.shape2_d_rectangle import Shape2DRectangle
from openapi_server.models.shape2_d_rectangle_text_block_all_of import Shape2DRectangleTextBlockAllOf
from openapi_server.models.style import Style
from openapi_server.models.transliteration import Transliteration
from openapi_server import util

from openapi_server.models.shape2_d_rectangle import Shape2DRectangle  # noqa: E501
from openapi_server.models.shape2_d_rectangle_text_block_all_of import Shape2DRectangleTextBlockAllOf  # noqa: E501
from openapi_server.models.style import Style  # noqa: E501
from openapi_server.models.transliteration import Transliteration  # noqa: E501

class Shape2DRectangleTextBlock(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, shape_id=None, shape_type=None, top=None, left=None, right=None, bottom=None, transliteration=None, style=None):  # noqa: E501
        """Shape2DRectangleTextBlock - a model defined in OpenAPI

        :param shape_id: The shape_id of this Shape2DRectangleTextBlock.  # noqa: E501
        :type shape_id: str
        :param shape_type: The shape_type of this Shape2DRectangleTextBlock.  # noqa: E501
        :type shape_type: str
        :param top: The top of this Shape2DRectangleTextBlock.  # noqa: E501
        :type top: int
        :param left: The left of this Shape2DRectangleTextBlock.  # noqa: E501
        :type left: int
        :param right: The right of this Shape2DRectangleTextBlock.  # noqa: E501
        :type right: int
        :param bottom: The bottom of this Shape2DRectangleTextBlock.  # noqa: E501
        :type bottom: int
        :param transliteration: The transliteration of this Shape2DRectangleTextBlock.  # noqa: E501
        :type transliteration: Transliteration
        :param style: The style of this Shape2DRectangleTextBlock.  # noqa: E501
        :type style: Style
        """
        self.openapi_types = {
            'shape_id': str,
            'shape_type': str,
            'top': int,
            'left': int,
            'right': int,
            'bottom': int,
            'transliteration': Transliteration,
            'style': Style
        }

        self.attribute_map = {
            'shape_id': 'shapeId',
            'shape_type': 'shapeType',
            'top': 'top',
            'left': 'left',
            'right': 'right',
            'bottom': 'bottom',
            'transliteration': 'transliteration',
            'style': 'style'
        }

        self._shape_id = shape_id
        self._shape_type = shape_type
        self._top = top
        self._left = left
        self._right = right
        self._bottom = bottom
        self._transliteration = transliteration
        self._style = style

    @classmethod
    def from_dict(cls, dikt) -> 'Shape2DRectangleTextBlock':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Shape2DRectangleTextBlock of this Shape2DRectangleTextBlock.  # noqa: E501
        :rtype: Shape2DRectangleTextBlock
        """
        return util.deserialize_model(dikt, cls)

    @property
    def shape_id(self):
        """Gets the shape_id of this Shape2DRectangleTextBlock.

        [TBD] Alpha-numeric, unique id of dataset  # noqa: E501

        :return: The shape_id of this Shape2DRectangleTextBlock.
        :rtype: str
        """
        return self._shape_id

    @shape_id.setter
    def shape_id(self, shape_id):
        """Sets the shape_id of this Shape2DRectangleTextBlock.

        [TBD] Alpha-numeric, unique id of dataset  # noqa: E501

        :param shape_id: The shape_id of this Shape2DRectangleTextBlock.
        :type shape_id: str
        """
        if shape_id is None:
            raise ValueError("Invalid value for `shape_id`, must not be `None`")  # noqa: E501

        self._shape_id = shape_id

    @property
    def shape_type(self):
        """Gets the shape_type of this Shape2DRectangleTextBlock.

        descriminator  # noqa: E501

        :return: The shape_type of this Shape2DRectangleTextBlock.
        :rtype: str
        """
        return self._shape_type

    @shape_type.setter
    def shape_type(self, shape_type):
        """Sets the shape_type of this Shape2DRectangleTextBlock.

        descriminator  # noqa: E501

        :param shape_type: The shape_type of this Shape2DRectangleTextBlock.
        :type shape_type: str
        """
        if shape_type is None:
            raise ValueError("Invalid value for `shape_type`, must not be `None`")  # noqa: E501

        self._shape_type = shape_type

    @property
    def top(self):
        """Gets the top of this Shape2DRectangleTextBlock.

        Top coordinate of the tag, relative to media raster  # noqa: E501

        :return: The top of this Shape2DRectangleTextBlock.
        :rtype: int
        """
        return self._top

    @top.setter
    def top(self, top):
        """Sets the top of this Shape2DRectangleTextBlock.

        Top coordinate of the tag, relative to media raster  # noqa: E501

        :param top: The top of this Shape2DRectangleTextBlock.
        :type top: int
        """

        self._top = top

    @property
    def left(self):
        """Gets the left of this Shape2DRectangleTextBlock.

        Left coordinate of the tag, relative to media raster  # noqa: E501

        :return: The left of this Shape2DRectangleTextBlock.
        :rtype: int
        """
        return self._left

    @left.setter
    def left(self, left):
        """Sets the left of this Shape2DRectangleTextBlock.

        Left coordinate of the tag, relative to media raster  # noqa: E501

        :param left: The left of this Shape2DRectangleTextBlock.
        :type left: int
        """

        self._left = left

    @property
    def right(self):
        """Gets the right of this Shape2DRectangleTextBlock.

        Right coordinate of the tag, relative to media raster  # noqa: E501

        :return: The right of this Shape2DRectangleTextBlock.
        :rtype: int
        """
        return self._right

    @right.setter
    def right(self, right):
        """Sets the right of this Shape2DRectangleTextBlock.

        Right coordinate of the tag, relative to media raster  # noqa: E501

        :param right: The right of this Shape2DRectangleTextBlock.
        :type right: int
        """

        self._right = right

    @property
    def bottom(self):
        """Gets the bottom of this Shape2DRectangleTextBlock.

        Bottom coordinate of the tag, relative to media raster  # noqa: E501

        :return: The bottom of this Shape2DRectangleTextBlock.
        :rtype: int
        """
        return self._bottom

    @bottom.setter
    def bottom(self, bottom):
        """Sets the bottom of this Shape2DRectangleTextBlock.

        Bottom coordinate of the tag, relative to media raster  # noqa: E501

        :param bottom: The bottom of this Shape2DRectangleTextBlock.
        :type bottom: int
        """

        self._bottom = bottom

    @property
    def transliteration(self):
        """Gets the transliteration of this Shape2DRectangleTextBlock.


        :return: The transliteration of this Shape2DRectangleTextBlock.
        :rtype: Transliteration
        """
        return self._transliteration

    @transliteration.setter
    def transliteration(self, transliteration):
        """Sets the transliteration of this Shape2DRectangleTextBlock.


        :param transliteration: The transliteration of this Shape2DRectangleTextBlock.
        :type transliteration: Transliteration
        """

        self._transliteration = transliteration

    @property
    def style(self):
        """Gets the style of this Shape2DRectangleTextBlock.


        :return: The style of this Shape2DRectangleTextBlock.
        :rtype: Style
        """
        return self._style

    @style.setter
    def style(self, style):
        """Sets the style of this Shape2DRectangleTextBlock.


        :param style: The style of this Shape2DRectangleTextBlock.
        :type style: Style
        """

        self._style = style
