# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.point2_d import Point2D
from openapi_server.models.shape import Shape
from openapi_server.models.shape2_d_timebound_polygon_all_of import Shape2DTimeboundPolygonAllOf
from openapi_server import util

from openapi_server.models.point2_d import Point2D  # noqa: E501
from openapi_server.models.shape import Shape  # noqa: E501
from openapi_server.models.shape2_d_timebound_polygon_all_of import Shape2DTimeboundPolygonAllOf  # noqa: E501

class Shape2DTimeboundPolygon(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, shape_id=None, shape_type=None, start_frame_counter=None, end_frame_counter=None, points=None):  # noqa: E501
        """Shape2DTimeboundPolygon - a model defined in OpenAPI

        :param shape_id: The shape_id of this Shape2DTimeboundPolygon.  # noqa: E501
        :type shape_id: str
        :param shape_type: The shape_type of this Shape2DTimeboundPolygon.  # noqa: E501
        :type shape_type: str
        :param start_frame_counter: The start_frame_counter of this Shape2DTimeboundPolygon.  # noqa: E501
        :type start_frame_counter: int
        :param end_frame_counter: The end_frame_counter of this Shape2DTimeboundPolygon.  # noqa: E501
        :type end_frame_counter: int
        :param points: The points of this Shape2DTimeboundPolygon.  # noqa: E501
        :type points: List[Point2D]
        """
        self.openapi_types = {
            'shape_id': str,
            'shape_type': str,
            'start_frame_counter': int,
            'end_frame_counter': int,
            'points': List[Point2D]
        }

        self.attribute_map = {
            'shape_id': 'shapeId',
            'shape_type': 'shapeType',
            'start_frame_counter': 'startFrameCounter',
            'end_frame_counter': 'endFrameCounter',
            'points': 'points'
        }

        self._shape_id = shape_id
        self._shape_type = shape_type
        self._start_frame_counter = start_frame_counter
        self._end_frame_counter = end_frame_counter
        self._points = points

    @classmethod
    def from_dict(cls, dikt) -> 'Shape2DTimeboundPolygon':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Shape2DTimeboundPolygon of this Shape2DTimeboundPolygon.  # noqa: E501
        :rtype: Shape2DTimeboundPolygon
        """
        return util.deserialize_model(dikt, cls)

    @property
    def shape_id(self):
        """Gets the shape_id of this Shape2DTimeboundPolygon.

        [TBD] Alpha-numeric, unique id of dataset  # noqa: E501

        :return: The shape_id of this Shape2DTimeboundPolygon.
        :rtype: str
        """
        return self._shape_id

    @shape_id.setter
    def shape_id(self, shape_id):
        """Sets the shape_id of this Shape2DTimeboundPolygon.

        [TBD] Alpha-numeric, unique id of dataset  # noqa: E501

        :param shape_id: The shape_id of this Shape2DTimeboundPolygon.
        :type shape_id: str
        """
        if shape_id is None:
            raise ValueError("Invalid value for `shape_id`, must not be `None`")  # noqa: E501

        self._shape_id = shape_id

    @property
    def shape_type(self):
        """Gets the shape_type of this Shape2DTimeboundPolygon.

        descriminator  # noqa: E501

        :return: The shape_type of this Shape2DTimeboundPolygon.
        :rtype: str
        """
        return self._shape_type

    @shape_type.setter
    def shape_type(self, shape_type):
        """Sets the shape_type of this Shape2DTimeboundPolygon.

        descriminator  # noqa: E501

        :param shape_type: The shape_type of this Shape2DTimeboundPolygon.
        :type shape_type: str
        """
        if shape_type is None:
            raise ValueError("Invalid value for `shape_type`, must not be `None`")  # noqa: E501

        self._shape_type = shape_type

    @property
    def start_frame_counter(self):
        """Gets the start_frame_counter of this Shape2DTimeboundPolygon.

        Frame where the described tag begins  # noqa: E501

        :return: The start_frame_counter of this Shape2DTimeboundPolygon.
        :rtype: int
        """
        return self._start_frame_counter

    @start_frame_counter.setter
    def start_frame_counter(self, start_frame_counter):
        """Sets the start_frame_counter of this Shape2DTimeboundPolygon.

        Frame where the described tag begins  # noqa: E501

        :param start_frame_counter: The start_frame_counter of this Shape2DTimeboundPolygon.
        :type start_frame_counter: int
        """

        self._start_frame_counter = start_frame_counter

    @property
    def end_frame_counter(self):
        """Gets the end_frame_counter of this Shape2DTimeboundPolygon.

        Frame where the described tag begins  # noqa: E501

        :return: The end_frame_counter of this Shape2DTimeboundPolygon.
        :rtype: int
        """
        return self._end_frame_counter

    @end_frame_counter.setter
    def end_frame_counter(self, end_frame_counter):
        """Sets the end_frame_counter of this Shape2DTimeboundPolygon.

        Frame where the described tag begins  # noqa: E501

        :param end_frame_counter: The end_frame_counter of this Shape2DTimeboundPolygon.
        :type end_frame_counter: int
        """

        self._end_frame_counter = end_frame_counter

    @property
    def points(self):
        """Gets the points of this Shape2DTimeboundPolygon.


        :return: The points of this Shape2DTimeboundPolygon.
        :rtype: List[Point2D]
        """
        return self._points

    @points.setter
    def points(self, points):
        """Sets the points of this Shape2DTimeboundPolygon.


        :param points: The points of this Shape2DTimeboundPolygon.
        :type points: List[Point2D]
        """

        self._points = points
