# coding: utf-8

# flake8: noqa
"""
    DeepVISS TAG

    DeepVISS (Deep Vision Interoperability Specification Standard) allows several computer vision solutions to produce, consume and exchange events in the same format.  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Contact: office@deepviss.org
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

# import models into model package
from openapi_client.models.archived_shard import ArchivedShard
from openapi_client.models.assign_users_request import AssignUsersRequest
from openapi_client.models.avatar import Avatar
from openapi_client.models.challenge import Challenge
from openapi_client.models.challenge_access_type_enum import ChallengeAccessTypeEnum
from openapi_client.models.challenge_budget_request import ChallengeBudgetRequest
from openapi_client.models.challenge_budget_response import ChallengeBudgetResponse
from openapi_client.models.challenge_completion_percentage import ChallengeCompletionPercentage
from openapi_client.models.challenge_dataset_metadata import ChallengeDatasetMetadata
from openapi_client.models.challenge_stage import ChallengeStage
from openapi_client.models.challenge_statistics import ChallengeStatistics
from openapi_client.models.challenge_statistics_users_work_time import ChallengeStatisticsUsersWorkTime
from openapi_client.models.challenge_status_enum import ChallengeStatusEnum
from openapi_client.models.challenge_tenant_role_enum import ChallengeTenantRoleEnum
from openapi_client.models.dataset import Dataset
from openapi_client.models.dataset_storage_cost import DatasetStorageCost
from openapi_client.models.dataset_type_enum import DatasetTypeEnum
from openapi_client.models.dispatch_policy import DispatchPolicy
from openapi_client.models.edge import Edge
from openapi_client.models.evaluation import Evaluation
from openapi_client.models.evaluation_policy import EvaluationPolicy
from openapi_client.models.get_task_response import GetTaskResponse
from openapi_client.models.image import Image
from openapi_client.models.internal_subjective_opinion import InternalSubjectiveOpinion
from openapi_client.models.latent_symbol import LatentSymbol
from openapi_client.models.life_form_enum import LifeFormEnum
from openapi_client.models.media_descriptor import MediaDescriptor
from openapi_client.models.media_item import MediaItem
from openapi_client.models.merged_tag import MergedTag
from openapi_client.models.observable_symbol import ObservableSymbol
from openapi_client.models.patch_challenge import PatchChallenge
from openapi_client.models.permanent_identifier import PermanentIdentifier
from openapi_client.models.permanent_identifier_segment import PermanentIdentifierSegment
from openapi_client.models.point2_d import Point2D
from openapi_client.models.point3_d import Point3D
from openapi_client.models.shape import Shape
from openapi_client.models.shape2_d_polygon import Shape2DPolygon
from openapi_client.models.shape2_d_polygon_all_of import Shape2DPolygonAllOf
from openapi_client.models.shape2_d_polygon_text_block import Shape2DPolygonTextBlock
from openapi_client.models.shape2_d_rectangle import Shape2DRectangle
from openapi_client.models.shape2_d_rectangle_all_of import Shape2DRectangleAllOf
from openapi_client.models.shape2_d_rectangle_text_block import Shape2DRectangleTextBlock
from openapi_client.models.shape2_d_rectangle_text_block_all_of import Shape2DRectangleTextBlockAllOf
from openapi_client.models.shape2_d_timebound_polygon import Shape2DTimeboundPolygon
from openapi_client.models.shape2_d_timebound_polygon_all_of import Shape2DTimeboundPolygonAllOf
from openapi_client.models.shape_type_enum import ShapeTypeEnum
from openapi_client.models.sharding_descriptor import ShardingDescriptor
from openapi_client.models.style import Style
from openapi_client.models.subjective_opinion import SubjectiveOpinion
from openapi_client.models.tag import Tag
from openapi_client.models.tagged_media_item import TaggedMediaItem
from openapi_client.models.task import Task
from openapi_client.models.task_resolution import TaskResolution
from openapi_client.models.transliteration import Transliteration
