# coding: utf-8

"""
    DeepVISS TAG

    DeepVISS (Deep Vision Interoperability Specification Standard) allows several computer vision solutions to produce, consume and exchange events in the same format.  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Contact: office@deepviss.org
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class MediaDescriptor(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'size': 'int',
        'hash': 'str',
        'p_hash': 'str'
    }

    attribute_map = {
        'size': 'size',
        'hash': 'hash',
        'p_hash': 'pHash'
    }

    def __init__(self, size=None, hash=None, p_hash=None, local_vars_configuration=None):  # noqa: E501
        """MediaDescriptor - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._size = None
        self._hash = None
        self._p_hash = None
        self.discriminator = None

        if size is not None:
            self.size = size
        if hash is not None:
            self.hash = hash
        if p_hash is not None:
            self.p_hash = p_hash

    @property
    def size(self):
        """Gets the size of this MediaDescriptor.  # noqa: E501

        Size of files when represented in binary, without additional encoding. Used for de-duplication.  # noqa: E501

        :return: The size of this MediaDescriptor.  # noqa: E501
        :rtype: int
        """
        return self._size

    @size.setter
    def size(self, size):
        """Sets the size of this MediaDescriptor.

        Size of files when represented in binary, without additional encoding. Used for de-duplication.  # noqa: E501

        :param size: The size of this MediaDescriptor.  # noqa: E501
        :type: int
        """

        self._size = size

    @property
    def hash(self):
        """Gets the hash of this MediaDescriptor.  # noqa: E501

        Cryptographic hash of original file. Used for de-duplication.  # noqa: E501

        :return: The hash of this MediaDescriptor.  # noqa: E501
        :rtype: str
        """
        return self._hash

    @hash.setter
    def hash(self, hash):
        """Sets the hash of this MediaDescriptor.

        Cryptographic hash of original file. Used for de-duplication.  # noqa: E501

        :param hash: The hash of this MediaDescriptor.  # noqa: E501
        :type: str
        """

        self._hash = hash

    @property
    def p_hash(self):
        """Gets the p_hash of this MediaDescriptor.  # noqa: E501

        Perceptual representation of the content of the media. Used for de-duplication.  # noqa: E501

        :return: The p_hash of this MediaDescriptor.  # noqa: E501
        :rtype: str
        """
        return self._p_hash

    @p_hash.setter
    def p_hash(self, p_hash):
        """Sets the p_hash of this MediaDescriptor.

        Perceptual representation of the content of the media. Used for de-duplication.  # noqa: E501

        :param p_hash: The p_hash of this MediaDescriptor.  # noqa: E501
        :type: str
        """

        self._p_hash = p_hash

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MediaDescriptor):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, MediaDescriptor):
            return True

        return self.to_dict() != other.to_dict()
