# coding: utf-8

"""
    DeepVISS TAG

    DeepVISS (Deep Vision Interoperability Specification Standard) allows several computer vision solutions to produce, consume and exchange events in the same format.  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Contact: office@deepviss.org
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class Shape2DRectangleAllOf(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'top': 'int',
        'left': 'int',
        'right': 'int',
        'bottom': 'int'
    }

    attribute_map = {
        'top': 'top',
        'left': 'left',
        'right': 'right',
        'bottom': 'bottom'
    }

    def __init__(self, top=None, left=None, right=None, bottom=None, local_vars_configuration=None):  # noqa: E501
        """Shape2DRectangleAllOf - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._top = None
        self._left = None
        self._right = None
        self._bottom = None
        self.discriminator = None

        if top is not None:
            self.top = top
        if left is not None:
            self.left = left
        if right is not None:
            self.right = right
        if bottom is not None:
            self.bottom = bottom

    @property
    def top(self):
        """Gets the top of this Shape2DRectangleAllOf.  # noqa: E501

        Top coordinate of the tag, relative to media raster  # noqa: E501

        :return: The top of this Shape2DRectangleAllOf.  # noqa: E501
        :rtype: int
        """
        return self._top

    @top.setter
    def top(self, top):
        """Sets the top of this Shape2DRectangleAllOf.

        Top coordinate of the tag, relative to media raster  # noqa: E501

        :param top: The top of this Shape2DRectangleAllOf.  # noqa: E501
        :type: int
        """

        self._top = top

    @property
    def left(self):
        """Gets the left of this Shape2DRectangleAllOf.  # noqa: E501

        Left coordinate of the tag, relative to media raster  # noqa: E501

        :return: The left of this Shape2DRectangleAllOf.  # noqa: E501
        :rtype: int
        """
        return self._left

    @left.setter
    def left(self, left):
        """Sets the left of this Shape2DRectangleAllOf.

        Left coordinate of the tag, relative to media raster  # noqa: E501

        :param left: The left of this Shape2DRectangleAllOf.  # noqa: E501
        :type: int
        """

        self._left = left

    @property
    def right(self):
        """Gets the right of this Shape2DRectangleAllOf.  # noqa: E501

        Right coordinate of the tag, relative to media raster  # noqa: E501

        :return: The right of this Shape2DRectangleAllOf.  # noqa: E501
        :rtype: int
        """
        return self._right

    @right.setter
    def right(self, right):
        """Sets the right of this Shape2DRectangleAllOf.

        Right coordinate of the tag, relative to media raster  # noqa: E501

        :param right: The right of this Shape2DRectangleAllOf.  # noqa: E501
        :type: int
        """

        self._right = right

    @property
    def bottom(self):
        """Gets the bottom of this Shape2DRectangleAllOf.  # noqa: E501

        Bottom coordinate of the tag, relative to media raster  # noqa: E501

        :return: The bottom of this Shape2DRectangleAllOf.  # noqa: E501
        :rtype: int
        """
        return self._bottom

    @bottom.setter
    def bottom(self, bottom):
        """Sets the bottom of this Shape2DRectangleAllOf.

        Bottom coordinate of the tag, relative to media raster  # noqa: E501

        :param bottom: The bottom of this Shape2DRectangleAllOf.  # noqa: E501
        :type: int
        """

        self._bottom = bottom

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Shape2DRectangleAllOf):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Shape2DRectangleAllOf):
            return True

        return self.to_dict() != other.to_dict()
