/* tslint:disable */
/* eslint-disable */
/**
 * DeepVISS TAG
 * DeepVISS (Deep Vision Interoperability Specification Standard) allows several computer vision solutions to produce, consume and exchange events in the same format.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: office@deepviss.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum ChallengeTenantRoleEnum {
    SUPPLIER = 'SUPPLIER',
    BROKER = 'BROKER',
    DEMANDER = 'DEMANDER'
}

export function ChallengeTenantRoleEnumFromJSON(json: any): ChallengeTenantRoleEnum {
    return ChallengeTenantRoleEnumFromJSONTyped(json, false);
}

export function ChallengeTenantRoleEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChallengeTenantRoleEnum {
    return json as ChallengeTenantRoleEnum;
}

export function ChallengeTenantRoleEnumToJSON(value?: ChallengeTenantRoleEnum | null): any {
    return value as any;
}

