/* tslint:disable */
/* eslint-disable */
/**
 * DeepVISS TAG
 * DeepVISS (Deep Vision Interoperability Specification Standard) allows several computer vision solutions to produce, consume and exchange events in the same format.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: office@deepviss.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum ChallengeStatusEnum {
    Pending = 'pending',
    InProgress = 'inProgress',
    Completed = 'completed',
    Rejected = 'rejected'
}

export function ChallengeStatusEnumFromJSON(json: any): ChallengeStatusEnum {
    return ChallengeStatusEnumFromJSONTyped(json, false);
}

export function ChallengeStatusEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChallengeStatusEnum {
    return json as ChallengeStatusEnum;
}

export function ChallengeStatusEnumToJSON(value?: ChallengeStatusEnum | null): any {
    return value as any;
}

