/* tslint:disable */
/* eslint-disable */
/**
 * DeepVISS TAG
 * DeepVISS (Deep Vision Interoperability Specification Standard) allows several computer vision solutions to produce, consume and exchange events in the same format.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: office@deepviss.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum DatasetTypeEnum {
    RgbStaticPhoto = 'rgb-static-photo',
    RgbLivePhoto = 'rgb-live-photo',
    RgbVideo = 'rgb-video',
    AudioRgbVideo = 'audio-rgb-video',
    AudioOnly = 'audio-only',
    Text = 'text'
}

export function DatasetTypeEnumFromJSON(json: any): DatasetTypeEnum {
    return DatasetTypeEnumFromJSONTyped(json, false);
}

export function DatasetTypeEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): DatasetTypeEnum {
    return json as DatasetTypeEnum;
}

export function DatasetTypeEnumToJSON(value?: DatasetTypeEnum | null): any {
    return value as any;
}

