/* tslint:disable */
/* eslint-disable */
/**
 * DeepVISS TAG
 * DeepVISS (Deep Vision Interoperability Specification Standard) allows several computer vision solutions to produce, consume and exchange events in the same format.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: office@deepviss.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Three independent counters corresponding to belief, disbelief and uncertainty. mediated by a common denominator and multiplied by a base rate (probability in the absence of this information).
 * @export
 * @interface InternalSubjectiveOpinion
 */
export interface InternalSubjectiveOpinion {
    /**
     * Functional source, if any, for this opinion, such a specific condition 
     * @type {string}
     * @memberof InternalSubjectiveOpinion
     */
    opinionEmitterId?: string;
    /**
     * Reason evoked, invoked or inferred by source for this opinion.
     * @type {string}
     * @memberof InternalSubjectiveOpinion
     */
    opinionReasonId?: string;
    /**
     * Number, signed and additive, of fulfillment points out of total that are attributed to belief that the opinion is TRUE. belief mass (bx) numerator accumulator.
     * @type {number}
     * @memberof InternalSubjectiveOpinion
     */
    attributedBeliefNumerator?: number;
    /**
     * Number, signed and additive, of fulfillment points out of total that are attributed to belief that the opinion is FALSE. belief mass (dx) numerator accumulator
     * @type {number}
     * @memberof InternalSubjectiveOpinion
     */
    attributedDisbeliefNumerator?: number;
    /**
     * Number, signed and additive, of fulfillment points out of total that are unattributed to either belief or disbelief and thus represent uncertainty. uncertainty mass (ux) numerator accumulator.
     * @type {number}
     * @memberof InternalSubjectiveOpinion
     */
    unattributedUncertaintyNumerator?: number;
    /**
     * The normalizing factor (the common denominator) of uncertainty, belief and disbelief.
     * @type {number}
     * @memberof InternalSubjectiveOpinion
     */
    commonDenominator?: number;
    /**
     * The probability of the opinion being true in the absence of the information generating it; this represents the default probability of a an element or character or letter appearing in a specific context
     * @type {number}
     * @memberof InternalSubjectiveOpinion
     */
    baseRateNumerator?: number;
}

export function InternalSubjectiveOpinionFromJSON(json: any): InternalSubjectiveOpinion {
    return InternalSubjectiveOpinionFromJSONTyped(json, false);
}

export function InternalSubjectiveOpinionFromJSONTyped(json: any, ignoreDiscriminator: boolean): InternalSubjectiveOpinion {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'opinionEmitterId': !exists(json, 'opinionEmitterId') ? undefined : json['opinionEmitterId'],
        'opinionReasonId': !exists(json, 'opinionReasonId') ? undefined : json['opinionReasonId'],
        'attributedBeliefNumerator': !exists(json, 'attributedBeliefNumerator') ? undefined : json['attributedBeliefNumerator'],
        'attributedDisbeliefNumerator': !exists(json, 'attributedDisbeliefNumerator') ? undefined : json['attributedDisbeliefNumerator'],
        'unattributedUncertaintyNumerator': !exists(json, 'unattributedUncertaintyNumerator') ? undefined : json['unattributedUncertaintyNumerator'],
        'commonDenominator': !exists(json, 'commonDenominator') ? undefined : json['commonDenominator'],
        'baseRateNumerator': !exists(json, 'baseRateNumerator') ? undefined : json['baseRateNumerator'],
    };
}

export function InternalSubjectiveOpinionToJSON(value?: InternalSubjectiveOpinion | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'opinionEmitterId': value.opinionEmitterId,
        'opinionReasonId': value.opinionReasonId,
        'attributedBeliefNumerator': value.attributedBeliefNumerator,
        'attributedDisbeliefNumerator': value.attributedDisbeliefNumerator,
        'unattributedUncertaintyNumerator': value.unattributedUncertaintyNumerator,
        'commonDenominator': value.commonDenominator,
        'baseRateNumerator': value.baseRateNumerator,
    };
}


