/* tslint:disable */
/* eslint-disable */
/**
 * DeepVISS TAG
 * DeepVISS (Deep Vision Interoperability Specification Standard) allows several computer vision solutions to produce, consume and exchange events in the same format.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: office@deepviss.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Point2D
 */
export interface Point2D {
    /**
     * X-coordinate as integer number of pixels measured from the left to the right.
     * @type {number}
     * @memberof Point2D
     */
    x: number;
    /**
     * Y-coordinate as integer number of pixels measured from the top to the bottom.
     * @type {number}
     * @memberof Point2D
     */
    y: number;
}

export function Point2DFromJSON(json: any): Point2D {
    return Point2DFromJSONTyped(json, false);
}

export function Point2DFromJSONTyped(json: any, ignoreDiscriminator: boolean): Point2D {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'x': json['x'],
        'y': json['y'],
    };
}

export function Point2DToJSON(value?: Point2D | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'x': value.x,
        'y': value.y,
    };
}


