/* tslint:disable */
/* eslint-disable */
/**
 * DeepVISS TAG
 * DeepVISS (Deep Vision Interoperability Specification Standard) allows several computer vision solutions to produce, consume and exchange events in the same format.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: office@deepviss.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Point2D,
    Point2DFromJSON,
    Point2DFromJSONTyped,
    Point2DToJSON,
    Shape2DPolygon,
    Shape2DPolygonFromJSON,
    Shape2DPolygonFromJSONTyped,
    Shape2DPolygonToJSON,
    Shape2DRectangleTextBlockAllOf,
    Shape2DRectangleTextBlockAllOfFromJSON,
    Shape2DRectangleTextBlockAllOfFromJSONTyped,
    Shape2DRectangleTextBlockAllOfToJSON,
    Style,
    StyleFromJSON,
    StyleFromJSONTyped,
    StyleToJSON,
    Transliteration,
    TransliterationFromJSON,
    TransliterationFromJSONTyped,
    TransliterationToJSON,
} from './';

/**
 * 
 * @export
 * @interface Shape2DPolygonTextBlock
 */
export interface Shape2DPolygonTextBlock extends Shape2DPolygon {
    /**
     * 
     * @type {Transliteration}
     * @memberof Shape2DPolygonTextBlock
     */
    transliteration?: Transliteration;
    /**
     * 
     * @type {Style}
     * @memberof Shape2DPolygonTextBlock
     */
    style?: Style;
}

export function Shape2DPolygonTextBlockFromJSON(json: any): Shape2DPolygonTextBlock {
    return Shape2DPolygonTextBlockFromJSONTyped(json, false);
}

export function Shape2DPolygonTextBlockFromJSONTyped(json: any, ignoreDiscriminator: boolean): Shape2DPolygonTextBlock {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        ...Shape2DPolygonFromJSONTyped(json, ignoreDiscriminator),
        'transliteration': !exists(json, 'transliteration') ? undefined : TransliterationFromJSON(json['transliteration']),
        'style': !exists(json, 'style') ? undefined : StyleFromJSON(json['style']),
    };
}

export function Shape2DPolygonTextBlockToJSON(value?: Shape2DPolygonTextBlock | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        ...Shape2DPolygonToJSON(value),
        'transliteration': TransliterationToJSON(value.transliteration),
        'style': StyleToJSON(value.style),
    };
}


