/* tslint:disable */
/* eslint-disable */
/**
 * DeepVISS TAG
 * DeepVISS (Deep Vision Interoperability Specification Standard) allows several computer vision solutions to produce, consume and exchange events in the same format.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: office@deepviss.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Point2D,
    Point2DFromJSON,
    Point2DFromJSONTyped,
    Point2DToJSON,
} from './';

/**
 * 
 * @export
 * @interface Shape2DTimeboundPolygonAllOf
 */
export interface Shape2DTimeboundPolygonAllOf {
    /**
     * Frame where the described tag begins
     * @type {number}
     * @memberof Shape2DTimeboundPolygonAllOf
     */
    startFrameCounter?: number;
    /**
     * Frame where the described tag begins
     * @type {number}
     * @memberof Shape2DTimeboundPolygonAllOf
     */
    endFrameCounter?: number;
    /**
     * 
     * @type {Array<Point2D>}
     * @memberof Shape2DTimeboundPolygonAllOf
     */
    points?: Array<Point2D>;
}

export function Shape2DTimeboundPolygonAllOfFromJSON(json: any): Shape2DTimeboundPolygonAllOf {
    return Shape2DTimeboundPolygonAllOfFromJSONTyped(json, false);
}

export function Shape2DTimeboundPolygonAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): Shape2DTimeboundPolygonAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'startFrameCounter': !exists(json, 'startFrameCounter') ? undefined : json['startFrameCounter'],
        'endFrameCounter': !exists(json, 'endFrameCounter') ? undefined : json['endFrameCounter'],
        'points': !exists(json, 'points') ? undefined : ((json['points'] as Array<any>).map(Point2DFromJSON)),
    };
}

export function Shape2DTimeboundPolygonAllOfToJSON(value?: Shape2DTimeboundPolygonAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'startFrameCounter': value.startFrameCounter,
        'endFrameCounter': value.endFrameCounter,
        'points': value.points === undefined ? undefined : ((value.points as Array<any>).map(Point2DToJSON)),
    };
}


