/* tslint:disable */
/* eslint-disable */
/**
 * DeepVISS TAG
 * DeepVISS (Deep Vision Interoperability Specification Standard) allows several computer vision solutions to produce, consume and exchange events in the same format.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: office@deepviss.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * The confidence of a merged tag (from several tags) or the overall.
 * @export
 * @interface ShardingDescriptor
 */
export interface ShardingDescriptor {
    /**
     * TBD
     * @type {number}
     * @memberof ShardingDescriptor
     */
    block?: number;
    /**
     * TBD
     * @type {number}
     * @memberof ShardingDescriptor
     */
    shard?: number;
}

export function ShardingDescriptorFromJSON(json: any): ShardingDescriptor {
    return ShardingDescriptorFromJSONTyped(json, false);
}

export function ShardingDescriptorFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShardingDescriptor {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'block': !exists(json, 'block') ? undefined : json['block'],
        'shard': !exists(json, 'shard') ? undefined : json['shard'],
    };
}

export function ShardingDescriptorToJSON(value?: ShardingDescriptor | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'block': value.block,
        'shard': value.shard,
    };
}


