# coding: utf-8

"""
    DeepVISS TAG

    DeepVISS (Deep Vision Interoperability Specification Standard) allows several computer vision solutions to produce, consume and exchange events in the same format.  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Contact: office@deepviss.org
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.media_item import MediaItem  # noqa: E501
from openapi_client.rest import ApiException

class TestMediaItem(unittest.TestCase):
    """MediaItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test MediaItem
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.media_item.MediaItem()  # noqa: E501
        if include_optional :
            return MediaItem(
                media_item_id = 'UERE80768EF053898993DD196397EDFDDFBC81751818B7FD1300124455B07E91CB289F87791D78064ECC93754F19B13D419489F162A150A22DD814CKAF0E', 
                type = 'rgb-static-photo', 
                format = 'image/heif', 
                descriptor = openapi_client.models.media_descriptor.MediaDescriptor(
                    size = 1345789, 
                    hash = 'FGX8993DD196397EDFDDFBC81751818B7FD1300124455B07E91CB289F87791D78064ECC93754F19B13D419489F162A150A22DD814CKAF0E', 
                    p_hash = 'pre', ), 
                sharding = openapi_client.models.sharding_descriptor.ShardingDescriptor(
                    block = 56, 
                    shard = 56, ), 
                image = openapi_client.models.image.Image(
                    image_url = '0', 
                    image_base64 = '0', 
                    image_content_type = '0', )
            )
        else :
            return MediaItem(
        )

    def testMediaItem(self):
        """Test MediaItem"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
