# coding: utf-8

"""
    DeepVISS TAG

    DeepVISS (Deep Vision Interoperability Specification Standard) allows several computer vision solutions to produce, consume and exchange events in the same format.  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Contact: office@deepviss.org
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.subjective_opinion import SubjectiveOpinion  # noqa: E501
from openapi_client.rest import ApiException

class TestSubjectiveOpinion(unittest.TestCase):
    """SubjectiveOpinion unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test SubjectiveOpinion
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.subjective_opinion.SubjectiveOpinion()  # noqa: E501
        if include_optional :
            return SubjectiveOpinion(
                opinion_emitter_id = 'ocr', 
                opinion_reason_id = 'unreadable', 
                belief = 0.75, 
                disbelief = 0.2, 
                uncertainty = 0.1, 
                base_rate_probability = 0.001
            )
        else :
            return SubjectiveOpinion(
        )

    def testSubjectiveOpinion(self):
        """Test SubjectiveOpinion"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
