# coding: utf-8

"""
    DeepVISS TAG

    DeepVISS (Deep Vision Interoperability Specification Standard) allows several computer vision solutions to produce, consume and exchange events in the same format.  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Contact: office@deepviss.org
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.task_api import TaskApi  # noqa: E501
from openapi_client.rest import ApiException


class TestTaskApi(unittest.TestCase):
    """TaskApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.task_api.TaskApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_task(self):
        """Test case for get_task

        Get new task  # noqa: E501
        """
        pass

    def test_submit_task(self):
        """Test case for submit_task

        Submit  task  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
